[package]
name = "ri-rust"
version = "0.1.0"
authors = ["Nasr Maswood <nasr@labelbox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
